<a href="https://colab.research.google.com/github/agyl05/projek-TBI/blob/main/Project_TBI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install sastrawi
!pip install nltk
!pip install fasttext
import pandas as pd
import random
import fasttext
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics.pairwise import cosine_similarity
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

Collecting sastrawi
  Downloading Sastrawi-1.0.1-py2.py3-none-any.whl.metadata (909 bytes)
Downloading Sastrawi-1.0.1-py2.py3-none-any.whl (209 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.7/209.7 kB 7.7 MB/s eta 0:00:00
Installing collected packages: sastrawi
Successfully installed sastrawi-1.0.1
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.1)
Collecting fasttext
  Downloading fasttext-0.9.3.tar.gz (73 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.4/73.4 kB 3.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pybind11>=2.2 (from fasttext)
  Using cached pybind11-3.0.1-py3-none-any.whl.metadata (10.0 kB)
Requirement already satisfied: setuptools>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from fasttext) (75.2.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from fasttext) (2.0.2)
Using cached pybind11-3.0.1-py3-none-any.whl (293 kB)
Building wheels for collected packages: fasttext
  Building wheel for fasttext (pyproject.toml) ... done
  Created wheel for fasttext: filename=fasttext-0.9.3-cp312-cp312-linux_x86_64.whl size=4498212 sha256=f1769c89e05b86d97411168738d7be1006531c293384441ef15416fb8d29e453
  Stored in directory: /root/.cache/pip/wheels/20/27/95/a7baf1b435f1cbde017cabdf1e9688526d2b0e929255a359c6
Successfully built fasttext
Installing collected packages: pybind11, fasttext
Successfully installed fasttext-0.9.3 pybind11-3.0.1

In [ ]:
from google.colab import files
files.upload()

Saving Diagnosa.csv to Diagnosa.csv

{'Diagnosa.csv': b'Diagnosa,Gejala,Penyakit,Penanganan,Risiko,,,,,,,,,,,,,,,,,,,,,\r\nAbses,Abses,Abses,1.000 unit dengan GUSANEX dan 8.000 ml dengan Dexatozoon Injeksi dan 8.000 ml dengan B-SANPLEX dan 8.000 ml dengan VIT-OXY LA,,,,,,,,,,,,,,,,,,,,,,\r\nAvitaminosis,"Anemia, Anorexia, Bulu Kusam, Demam, Diare, Gangguan otot , Gangguan pencernaan , Gangguan penglihatan, Gangguan pertumbuhan pada anak hewan, Gangguan pertumbuhan pada anak-anak, Gangguan reproduksi, Gangguan sistem kekebalan tubuh, Gangguan sistem saraf, Gangguan tulang, Keguguran pada betina, Kehilangan nafsu makan, Kejang , Kekurusan, Lelah , Lemah, Kerontokan rambut, Kesulitan dalam perkawinan, Masalah gigi dan gusi, seperti berdarah atau gusi yang bengkak, Masalah kulit seperti kering, bersisik, dan keriput, Masalah pernapasan, Penglihatan kabur, Perubahan perilaku, Pincang, Sakit otot, Sakit sendi, Sembelit",Avitaminosis,"1.000 bolus dengan PYRONIL-2500 BOLUS dan 8.000 ml dengan VITOL-140, 1000 dengan Pyronil-@2500 bolus dengan B-Sanplex, 1001 dengan Pyronil-@2500 bolus dengan B-Sanplex, 8.000 ml dengan VITOL, 1.000 bolus dengan PYRONIL-2500 BOLUS dan 10.000 ml dengan VITOL-140 dan 8.000 ml dengan BIODIN1003 dengan Pyronil-@2500 bolus dengan B-Sanplex2.000 ml dengan B-SANPLEX-140, 8.000 ml dengan B-SANPLEX dan 1.000 bolus dengan PYRONIL-2500 BOLUS, 1.000 bolus dengan PYRONIL-2500 BOLUS dan 10.000 ml dengan VITOL-140 dan 8.000 ml dengan BIODIN",Kekurangan vitamin (tidak terlalu beresiko),,,,,,,,,,,,,,,,,,,,,\r\nBabesiosis,"Bulu kusam,Gatal,Kelainan kulit,Perkulitan",Babesiosis,"8000 gram dengan TRYPONIL; @3000 ml dengan Intrafer-200 B12, 1000 gram dengan SUPER-P; @8000 ml dengan VITOL-140; dan @1000 ml dengan MEDOXY LA",,,,,,,,,,,,,,,,,,,,,,\r\nBovine Ephemeral Fever,"Anorexia, Demam, Demam, Demam, Diare, Durasi gejala biasanya 3-4 hari, Gemetar , Kaku pada otot-otot tubuh, Kebingungan, Kehilangan nafsu makan, Lemah, Kelesuan, Kemungkinan terjadinya kejang, Kesadaran menurun, Kesulitan berdiri, Kesulitan bergerak, Muntah , Pembengkakan pada sendi-sendi kaki, Penurunan produksi susu pada sapi perah, Penurunan suhu tubuh setelah demam, Pincang, Produksi air liur meningkat, Sakit otot , Sakit sendi, Sempoyongan, Terjadi kejang-kejang, Tremor",Bovine Ephemeral Fever,"10.000 ml dengan B-SANPLEX dan 1.000 bolus dengan PYRONIL-2500 BOLUS, 8.000 ml dengan VET-OXY LA dan 8.000 ml dengan SULPIDON INJEKSI dan 8.000 ml dengan B-SANPLEX, 10.000 ml dengan SULPIDON, 8001 ml dengan B-SANPLEX; @8000 ml dengan SULPIDO INJEKSI dan @8000 ml dengan VET-OXY LA8.000 ml dengan B-SANPLEX dan 10.000 ml dengan SULPIDON INJEKSI dan 8.000 ml dengan VET-OXY LAINJEKSI dan 8.000 ml dengan VET-OXY LA dan 8.000 ml dengan B-SANPLEX, 8001 ml dengan B-SANPLEX; @8000 ml dengan SULPIDO INJEKSI dan @8000 ml dengan VET-OXY LA",Bisa menurunkan produksi daging ,,,,,,,,,,,,,,,,,,,,,\r\nCorpus Luteum Persisten,Anestrus,Corpus Luteum Persisten,5000 ml dengan CAPRIGLADIN INJ; @10000 ml dengan VITOL-140,,,,,,,,,,,,,,,,,,,,,,\r\nDistokia,"gelisah, Janin yang terlilit tali pusar, Keluarnya cairan atau darah dalam jumlah yang tidak normal dari vulva, Kepala atau anggota badan janin terlihat tidak normal atau terdistorsi, Kesulitan dalam proses persalinan, Keterlambatan dalam proses persalinan, Lama waktu persalinan yang tidak normal, Pendarahan atau keluarnya cairan dari vulva, Posisi atau presentasi janin yang tidak benar (misalnya kepala tersendat), Posisi atau presentasi janin yang tidak benar (misalnya, kaki belakang), Sapi kesulitan untuk melahirkan, Sapi menunjukkan tanda-tanda kesakitan yang tidak biasa, Sapi merintih , Sapi tampak gelisah, Sapi tampak tidak nyaman",Distokia,"1.000 unit dengan Traksi dan 10.000 ml dengan PENSTREP-400 dan 8.000 ml dengan BIODIN, 3.000 ml dengan BIODIN dan 1.000 unit dengan 2.000 ml dengan VET-OXY LA dan 1.000 ml dengan OXYTOCIN",,,,,,,,,,,,,,,,,,,,,,\r\nEndometritis,Rahim bernanah,Endometritis,10000 ml dengan PENSTREP-400; @10000 ml dengan VITOL-140,,,,,,,,,,,,,,,,,,,,,,\r\nEnteritis,"Berat badan turun secara signifikan, Darah dalam tinja (terkadang), Dehidrasi , Demam, Diare, Diare, Gatal atau terasa seperti ada benda asing di mata, Gejala flu, seperti pilek atau sakit tenggorokan (pada beberapa kasus), Penurunan berat badan yang signifikan, Kehilangan nafsu makan, Lelah , Keluarnya sekresi atau mata berair, Kram perut atau nyeri perut, Kurangnya urin, Lemas, Mata cekung, Mata merah, Mata iritasi, Mencret, Mengedipkan mata lebih sering dari biasanya, Mual, Mulut kering, Muntah , Pembengkakan pada kelopak mata, Penglihatan kabur, Penurunan produksi susu pada hewan ternak (jika berlaku), Perubahan perilaku, Perut kembung, Produksi lendir atau nanah pada mata (terutama jika infeksi bakteri), Rasa nyeri atau ketidaknyamanan di mata, Sensasi panas di mata, Sensitivitas terhadap cahaya (fotofobia), Suhu tubuh yang meningkat",Enteritis,"2.000 ml dengan SULFA STRONG dan 2.000 ml dengan VITOL-140, 10.000 ml dengan SULFA STRONG dan 10.000 ml dengan BIODIN, 10.000 ml dengan SULFA STRONG dan 8.000 ml dengan VITOL-140, 2.000 ml dengan SULFA STRONG dan 2.000 ml dengan B-SANPLEX",,,,,,,,,,,,,,,,,,,,,,\r\nEutokia,"Lahir mati,Lahir normal,Tanda lain",Eutokia,"10.000 ml dengan SULFA STRONG dan 10.000 ml dengan BIODIN, 1000 bolus dengan LAGANTOR BSA BOLUS; @1000 ml dengan VITOL-140, 8000 ml dengan VITOL-140; @1000 ml dengan PYRONIL-2500 BOLUS",,,,,,,,,,,,,,,,,,,,,,\r\nFasciolosis,"Bulu kusam, Kekurusan, Rahang bawah bengkak",Fasciolosis,8000 ml dengan VITOL-140; @10000 ml dengan ABENOL-100 ORAL,,,,,,,,,,,,,,,,,,,,,,\r\nFeline Calicivirus,"Anorexia,Demam,Liur berlebihan,Sempoyongan",Feline Calicivirus,"0.300 ml dengan MEDOXY-L; @1000 ml dengan INJEKSI VITAMIN B12; dan @0.200 ml dengan PRODRYL INJ, 0.100 ml dengan PRODRYL INJ; @0.200 ml dengan MEDOXY-L; @1000 ml dengan Injekvit B Plex",,,,,,,,,,,,,,,,,,,,,,\r\nFeline Viral Rhinotracheitis,"Anorexia,Demam,Liur berlebihan",Feline Viral Rhinotracheitis,0.500 ml dengan PENSTREP-400; @ 0.500 ml  dengan Dexatozoom Injeksi; @0.500 ml dengan Hematodin,,,,,,,,,,,,,,,,,,,,,,\r\nFraktur,Patah tulang kaki,Fraktur,0.500 ml dengan Dexatozoom Injeksi; @0.500 ml dengan PENSTREP-400,,,,,,,,,,,,,,,,,,,,,,\r\nGinggivitis,Luka penis,Ginggivitis,10000 ml dengan Dexatozoom Injeksi; @ 10000 ml dengan VET-OXY SB,,,,,,,,,,,,,,,,,,,,,,\r\nHernia,"Hernia abdominalis, Hernia umbilicalis",Hernia,"0.500 ml dengan CATOSAL 10% (dulu CATOSAL INJEKSI 10%); @0.300 ml dengan KETAMINE 10% INJ; @0.300 ml dengan XYLA; @0.500 ml dengan Daxatozoom Injeksi; @0.500 ml dengan PENSTREP-400, 4000 ml dengan PENSTREP-400; @4000 ml dengan WONDER LIDOCAIN; @1000 unit dengan GUSANEX; @5000 ml dengan Dexatozoom Injeksi",,,,,,,,,,,,,,,,,,,,,,\r\nHipofungsi Ovari,"Anestrus,Kekurusan",Hipofungsi Ovari,10000 ml dengan ALBENOL-100 ORAL; @10000 ml dengan VITOL-140,,,,,,,,,,,,,,,,,,,,,,\r\nIndigesti,"Anorexia, Demam",Indigesti,"3000 ml dengan SULPIDON INJEKSI; @3000 ml dengan PENSTREP-400; @3000 ml dengan Hematodin, 3000 ml dengan PENSTREP-400; @3000 ml dengan SULPIDON INJEKSI; @3000 ml dengan INTROVIT-B-COMPLEX",,,,,,,,,,,,,,,,,,,,,,\r\nKawin Berulang,Kawin berulang,Kawin Berulang,8000 ml dengan VITOL-140; @10000 ml dengan ALBENOL-100 ORAL,,,,,,,,,,,,,,,,,,,,,,\r\nKecelakaan,"Buta,Luka berdarah,Pincang,Tanda lain",Kecelakaan,"0.500 ml dengan Dexatozoom Injeksi; @0.300 ml dengan KETAMINE 10% INJ; @0.300 ml dengan XYLA; @0.500 ml dengan Hematodin, 0.500 ml dengan PENSTREP-400; @0.300 ml dengan KETAMINE 10% INJ; @0.300 ml dengan XYLA;@0.500 ml dengan Dexatozoom Injeksi; @0.500 ml dengan GUSANEX, 10000 ml dengan Dexatozoom Injeksi; @10000 ml dengan VET-OXY SB, 8000 ml dengan VITOL-14-; @8000 ml dengan Dexatozoom Injeksi; @6000 ml dengan VET-OXY LA",,,,,,,,,,,,,,,,,,,,,,\r\nKeguguran,"Keguguran, Keguguran Muda, Lahir mati",Keguguran,3.000 ml dengan MEDOXY-L dan 3.000 ml dengan VITAMIN B-12 INJEKSI,,,,,,,,,,,,,,,,,,,,,,\r\nKekurangan Calsium,"Ambruk ,Kekukurusan",Kekurangan Calsium,12000 ml dengan BIODIN; @100000 ml dengan CALCIDEX PLUS,,,,,,,,,,,,,,,,,,,,,,\r\nKeracunan,"Anorexia, Lemah, Liur berlebihan, Mencret",Keracunan,2000 ml dengan COLIBACT INJEKSI; @1000 ml dengan ATROPIN SULFATE; @2000 ml dengan SULPIDON INJEKSI,,,,,,,,,,,,,,,,,,,,,,\r\nKeracunan Pestisida,"Anorexia, Lemah",Keracunan Pestisida,2000 ml dengan INTROVIT-B COMPLEX; @1000 ml dengan ATROPIN SULFATE; @2000 ml dengan VET-OXY SB,,,,,,,,,,,,,,,,,,,,,,\r\nKonjunctivitas,"Buta, Kornea Mata Keruh",Konjunctivitas,"0.300 ml dengan Dexatozoom Injeksi; @0.200 ml dengan XYLA; @0.200 ml dengan KETAMINE 10% INJ; @0.500 ml dengan PENSTREP-400, 0.500 ml dengan VET-OXY SB; @0.300 ml dengan Dexatozoom Injeksi",,,,,,,,,,,,,,,,,,,,,,\r\nMalnutrisi,"Anemia, Diare, Gangguan pada organ tubuh, seperti hati atau ginjal, Gangguan pencernaan seperti diare atau sembelit, Gangguan pencernaan seperti diare atau sembelit, Gangguan pertumbuhan pada anak-anak, Gangguan sistem saraf, Gangguan sistem kekebalan tubuh, Kegagalan organ tertentu karena kekurangan nutrisi tertentu, Kelelahan yang kronis, Lemah, Kelesuan, Kualitas bulu atau kulit yang buruk, seperti kerontokan bulu, kulit kering, atau luka yang sulit sembuh, Kulit kering dan bersisik, Masalah gigi dan gusi, seperti berdarah atau gusi yang bengkak, Masalah pada perkembangan otak pada anak-anak, Masalah reproduksi pada wanita, termasuk haid tidak teratur, Mata cekung, Penurunan berat badan yang signifikan, Rambut kering, Rambut mudah rontok, Sembelit",Malnutrisi,"1.000 bolus dengan PYRONIL-2500 BOLUS dan 10.000 ml dengan VITOL-140 dan 8.000 ml dengan BIODIN, 10.000 ml dengan VITOL-140 dan 8.000 ml dengan SULPIDON INJEKSI",,,,,,,,,,,,,,,,,,,,,,\r\nMastisis,"Abses, Ambing Bengkak, Anoresia, Liur Berlebihan",Mastisis,3000 ml dengan dexatazoninjeksi dan @3000 ml dengan sulfa strong,Bisa menyebabkan kematian,,,,,,,,,,,,,,,,,,,,,\r\nMiasis,"Bau busuk yang tidak sedap dari luka atau area terinfeksi, Gangguan umum dalam perilaku atau kesehatan, Hilangnya bulu atau rambut pada area yang terinfeksi, Penurunan berat badan, Kehilangan nafsu makan, Kemerahan, Luka Berdarah, Menggaruk atau menggosok bagian tubuh tertentu, Pembengkakan pada area terinfeksi, Pembentukan benjolan atau lepuh pada kulit, Peradangan kulit, Perilaku gelisah atau gatal, Sekresi cairan atau nanah dari area terinfeksi",Miasis,"2.000 ml dengan B-SANPLEX dan 2.000 ml dengan Limoxin 200 LA dan 1.000 unit dengan GUSANEX, 1.000 unit dengan GUSANEX dan 3.000 ml dengan Limoxin 200 LA dan 2.000 ml dengan VITOL-140",Beresiko keluar belatung jika semakin dibiarkan akan semakin membesar,,,,,,,,,,,,,,,,,,,,,\r\nOrf,"Kelainan mata, Kelainan mulut, Radang mata",Orf,"3000 ml dengan MEDOXY-L; @2000 ml dengan PRODRYL INJ; dan @3000 ml dengan JECTAVIT B12 INJ, 2000 ml dengan PRODRYL INJ; @2000 ml dengan MEDOXY LA; dan @3000 ml dengan VITAMIN B12 INJEKSI",,,,,,,,,,,,,,,,,,,,,,\r\nOtitis Interna,Radang telinga,Otitis Interna,"0.500 ml dengan MEDOXY-L; @1000 ml dengan VITAMIN B12 INJEKSI, 0.500 ml dengan Dexatozoom Injeksi; @0.500 ml dengan PENSTREP-400, 0.500 ml dengan PENSTREP-400; @0.500 ml dengan Dexatozoom Injeksi; @0.500 ml dengan CATOSAL 10% (dulu CATOSAL INJEKSI 10%)",,,,,,,,,,,,,,,,,,,,,,\r\nPapilloma,Kelainan kulit,Papilloma,3000 ml dengan Intermectin; @8000 ml dengan VITOL-140,,,,,,,,,,,,,,,,,,,,,,\r\nPneumonia,"Batuk, Kekurusan",Pneumonia,3000 ml dengan Hematodin; @3000 ml dengan Dexatozoom Injeksi; @3000 ml dengan INTRAMOX-150 LA,,,,,,,,,,,,,,,,,,,,,,\r\nProlapsus Dubur,Prolaps Anus,Prolapsus Dubur,0.300 ml dengan XYLA; @0.500 ml dengan Dexatozoom Injeksi; @1000 unit dengan GAUSSANEX; @0.500 ml dengan PENSTREP-400; @0.500 ml dengan KENTAMINE 10% INJ,,,,,,,,,,,,,,,,,,,,,,\r\nQ fever,"Ambing bengkak, Demam",Q fever,3000 ml dengan SULPIDON INJEKSI; @1000 ml dengan PENSTREP 400; @3000 ml dengan VITAMIN B12 INJEKSI,,,,,,,,,,,,,,,,,,,,,,\r\nRadang Mata,"Borok Perkulitan, Bulu Rontok, Daun Telinga Keropeng, Gatal atau terasa seperti ada benda asing di mata, Kelopak mata melekat saat bangun tidur (terutama pada konjungtivitis bakteri), Keluarnya sekresi , Kornea Mata Keruh, Mata berair, Mata berdarah, Mata iritasi, Mata merah , Mata terasa kering atau terasa pasir di mata, Mengedipkan mata lebih sering dari biasanya, Pembengkakan pada kelopak mata, Pengeluaran nanah dari mata, Penglihatan kabur, Perkulitan, Produksi lendir atau nanah pada mata (terutama jika infeksi bakteri), Rasa nyeri atau ketidaknyamanan di mata, Rasa perih atau sakit di mata, Sensasi panas di mata, Sensitivitas terhadap cahaya (fotofobia)",Radang Mata,"8000 ml dengan oxy-kella, 8001 ml dengan oxy-kella, 8002 ml dengan oxy-kella, 2.000 ml dengan VET-OXY LA dan 2.000 ml dengan VITOL-140, 10.000 ml dengan VET-OXY LA dan 8.000 ml dengan VITOL-140, 10.000 dengan Limoxin 200 LA dan  8.000 ml dengan Dexatozoon Injeksi 8.000 ml dengan VITOL-140, 8005 ml dengan oxy-kella","Beresiko kebutaan, tidak terlalu beresiko ",,,,,,,,,,,,,,,,,,,,,\r\nRetensio Secundarium,"Bau tidak sedap dari perdarahan vagina (baunya bisa menjadi busuk), Kenaikan suhu tubuh (demam), Nyeri atau kram perut bagian bawah, Perasaan penuh atau tertekan di perut bagian bawah, Perdarahan vagina yang berkepanjangan setelah persalinan, Retensi placenta",Retensio Secundarium,"8.000 ml deangan Dexatozoon Injeksi dan 10.000 ml dengan VET-OXY LA dan 8.000 ml dengan VITOL-140, 8.000 ml dengan Dexatozoon Injeksi dan 8.000 ml dengan VITOL-140 dan 8.000 ml dengan VET-OXY LA",,,,,,,,,,,,,,,,,,,,,,\r\nScabies,"Anorexia, Borok Perkulitan, Bulu Rontok, gatal, Perkulitan",Scabies,"0.0500 dengan ivomec super, 3.000 ml dengan injeksi VITAMIN B-12 dan 0.400 gram dengan SUPER-P",Bisa menghisap darah dan sangat beresiko yang langsung berkontrasi dengan sapi tersebut,,,,,,,,,,,,,,,,,,,,,\r\nSilent heart,anestrus,Silent heart,"5000 ml dengan CAPRIGLANDIN INJ; @10000 ml dengan VITOL-140, 5000 ml dengan LUTALYSE; @10000 ml dengan VITOL-140",,,,,,,,,,,,,,,,,,,,,,\r\nStomatitis,"Anorexia, Demam, Liur berdarah",Stomatitis,10000 ml dengan SULPIDON INJEKSI; @8000 ml dengan B-SANPLEX,,,,,,,,,,,,,,,,,,,,,,\r\nSurra,"Anorexia, Demam, Sempoyongan",Surra,10000 gram dengan TRYPONIL; @10000 ml dengan Hematodin,,,,,,,,,,,,,,,,,,,,,,\r\nTidak Sakit,"Tanda lain, Tidak Sakit",Tidak Sakit,8.000 ml dengan B-SANPLEX,,,,,,,,,,,,,,,,,,,,,,\r\nTympany,"Kegagalan hewan untuk makan atau minum, gelisah, Kehilangan nafsu makan, Kesulitan bergerak atau berdiri, Kesulitan bernapas, Keterlambatan dalam pengosongan perut, Mungkin terjadi bisingan pada rongga dada atau pernapasan yang cepat, Pernapasan cepat, Perut yang membesar secara tiba-tiba, Perut yang membuncit , Produksi ludah berlebihan, Sapi tampak gelisah, Sapi tampak tidak nyaman, Sering mengunyah atau menggerogoti benda-benda di sekitarnya, Suara perut yang berbunyi-bunyi",Tympany,"2.000 ml dengan SULPIDON INJEKSI dan 30.000 ml dengan Tympanol dan 2.000 ml dengan BIODIN, 3.000 ml dengan SULPIDON INJEKSI dan 30.000 ml dengan Tympanol dan 3.000 ml dengan B-SANPLEX, 3.000 ml dengan SULPIDON INJEKSI dan 30.000 ml dengan Tympanol dan 3.000 ml BIODIN",,,,,,,,,,,,,,,,,,,,,,\r\nUrolothiasis,Kesulitan kencing,Urolothiasis,0.500 ml dengan Dexatozoom Injeksi; @0.300 ml dengan KETAMINE 10% INJ; @0.300 ml dengan XYLA; @0.500 ml dengan PENSTREP-400,,,,,,,,,,,,,,,,,,,,,,\r\nAbses,Abses,Abses,1.000 unit dengan GUSANEX dan 8.000 ml dengan Dexatozoon Injeksi dan 8.000 ml dengan B-SANPLEX dan 8.000 ml dengan VIT-OXY LA,,,,,,,,,,,,,,,,,,,,,,\r\nAvitaminosis,"Anemia, Anorexia, Bulu Kusam, Demam, Diare, Gangguan otot , Gangguan pencernaan , Gangguan penglihatan, Gangguan pertumbuhan pada anak hewan, Gangguan pertumbuhan pada anak-anak, Gangguan reproduksi, Gangguan sistem kekebalan tubuh, Gangguan sistem saraf, Gangguan tulang, Keguguran pada betina, Kehilangan nafsu makan, Kejang , Kekurusan, Lelah , Lemah, Kerontokan rambut, Kesulitan dalam perkawinan, Masalah gigi dan gusi, seperti berdarah atau gusi yang bengkak, Masalah kulit seperti kering, bersisik, dan keriput, Masalah pernapasan, Penglihatan kabur, Perubahan perilaku, Pincang, Sakit otot, Sakit sendi, Sembelit",Avitaminosis,"1.000 bolus dengan PYRONIL-2500 BOLUS dan 8.000 ml dengan VITOL-140, 1000 dengan Pyronil-@2500 bolus dengan B-Sanplex, 1001 dengan Pyronil-@2500 bolus dengan B-Sanplex, 8.000 ml dengan VITOL, 1.000 bolus dengan PYRONIL-2500 BOLUS dan 10.000 ml dengan VITOL-140 dan 8.000 ml dengan BIODIN1003 dengan Pyronil-@2500 bolus dengan B-Sanplex2.000 ml dengan B-SANPLEX-140, 8.000 ml dengan B-SANPLEX dan 1.000 bolus dengan PYRONIL-2500 BOLUS, 1.000 bolus dengan PYRONIL-2500 BOLUS dan 10.000 ml dengan VITOL-140 dan 8.000 ml dengan BIODIN",Kekurangan vitamin (tidak terlalu beresiko),,,,,,,,,,,,,,,,,,,,,\r\nBabesiosis,"Bulu kusam,Gatal,Kelainan kulit,Perkulitan",Babesiosis,"8000 gram dengan TRYPONIL; @3000 ml dengan Intrafer-200 B12, 1000 gram dengan SUPER-P; @8000 ml dengan VITOL-140; dan @1000 ml dengan MEDOXY LA",,,,,,,,,,,,,,,,,,,,,,\r\nBovine Ephemeral Fever,"Anorexia, Demam, Demam, Demam, Diare, Durasi gejala biasanya 3-4 hari, Gemetar , Kaku pada otot-otot tubuh, Kebingungan, Kehilangan nafsu makan, Lemah, Kelesuan, Kemungkinan terjadinya kejang, Kesadaran menurun, Kesulitan berdiri, Kesulitan bergerak, Muntah , Pembengkakan pada sendi-sendi kaki, Penurunan produksi susu pada sapi perah, Penurunan suhu tubuh setelah demam, Pincang, Produksi air liur meningkat, Sakit otot , Sakit sendi, Sempoyongan, Terjadi kejang-kejang, Tremor",Bovine Ephemeral Fever,"10.000 ml dengan B-SANPLEX dan 1.000 bolus dengan PYRONIL-2500 BOLUS, 8.000 ml dengan VET-OXY LA dan 8.000 ml dengan SULPIDON INJEKSI dan 8.000 ml dengan B-SANPLEX, 10.000 ml dengan SULPIDON, 8001 ml dengan B-SANPLEX; @8000 ml dengan SULPIDO INJEKSI dan @8000 ml dengan VET-OXY LA8.000 ml dengan B-SANPLEX dan 10.000 ml dengan SULPIDON INJEKSI dan 8.000 ml dengan VET-OXY LAINJEKSI dan 8.000 ml dengan VET-OXY LA dan 8.000 ml dengan B-SANPLEX, 8001 ml dengan B-SANPLEX; @8000 ml dengan SULPIDO INJEKSI dan @8000 ml dengan VET-OXY LA",Bisa menurunkan produksi daging ,,,,,,,,,,,,,,,,,,,,,\r\nCorpus Luteum Persisten,Anestrus,Corpus Luteum Persisten,5000 ml dengan CAPRIGLADIN INJ; @10000 ml dengan VITOL-140,,,,,,,,,,,,,,,,,,,,,,\r\nDistokia,"gelisah, Janin yang terlilit tali pusar, Keluarnya cairan atau darah dalam jumlah yang tidak normal dari vulva, Kepala atau anggota badan janin terlihat tidak normal atau terdistorsi, Kesulitan dalam proses persalinan, Keterlambatan dalam proses persalinan, Lama waktu persalinan yang tidak normal, Pendarahan atau keluarnya cairan dari vulva, Posisi atau presentasi janin yang tidak benar (misalnya kepala tersendat), Posisi atau presentasi janin yang tidak benar (misalnya, kaki belakang), Sapi kesulitan untuk melahirkan, Sapi menunjukkan tanda-tanda kesakitan yang tidak biasa, Sapi merintih , Sapi tampak gelisah, Sapi tampak tidak nyaman",Distokia,"1.000 unit dengan Traksi dan 10.000 ml dengan PENSTREP-400 dan 8.000 ml dengan BIODIN, 3.000 ml dengan BIODIN dan 1.000 unit dengan 2.000 ml dengan VET-OXY LA dan 1.000 ml dengan OXYTOCIN",,,,,,,,,,,,,,,,,,,,,,\r\nEndometritis,Rahim bernanah,Endometritis,10000 ml dengan PENSTREP-400; @10000 ml dengan VITOL-140,,,,,,,,,,,,,,,,,,,,,,\r\nEnteritis,"Berat badan turun secara signifikan, Darah dalam tinja (terkadang), Dehidrasi , Demam, Diare, Diare, Gatal atau terasa seperti ada benda asing di mata, Gejala flu, seperti pilek atau sakit tenggorokan (pada beberapa kasus), Penurunan berat badan yang signifikan, Kehilangan nafsu makan, Lelah , Keluarnya sekresi atau mata berair, Kram perut atau nyeri perut, Kurangnya urin, Lemas, Mata cekung, Mata merah, Mata iritasi, Mencret, Mengedipkan mata lebih sering dari biasanya, Mual, Mulut kering, Muntah , Pembengkakan pada kelopak mata, Penglihatan kabur, Penurunan produksi susu pada hewan ternak (jika berlaku), Perubahan perilaku, Perut kembung, Produksi lendir atau nanah pada mata (terutama jika infeksi bakteri), Rasa nyeri atau ketidaknyamanan di mata, Sensasi panas di mata, Sensitivitas terhadap cahaya (fot

In [ ]:
# !unzip -o "archive (1).zip"

In [ ]:
df = pd.read_csv("Diagnosa.csv")
df.head()

,Diagnosa,Gejala,Penyakit,Penanganan,Risiko,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,Abses,Abses,Abses,1.000 unit dengan GUSANEX dan 8.000 ml dengan ...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Avitaminosis,"Anemia, Anorexia, Bulu Kusam, Demam, Diare, Ga...",Avitaminosis,1.000 bolus dengan PYRONIL-2500 BOLUS dan 8.00...,Kekurangan vitamin (tidak terlalu beresiko),NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Babesiosis,"Bulu kusam,Gatal,Kelainan kulit,Perkulitan",Babesiosis,8000 gram dengan TRYPONIL; @3000 ml dengan Int...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Bovine Ephemeral Fever,"Anorexia, Demam, Demam, Demam, Diare, Durasi g...",Bovine Ephemeral Fever,10.000 ml dengan B-SANPLEX dan 1.000 bolus den...,Bisa menurunkan produksi daging,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Corpus Luteum Persisten,Anestrus,Corpus Luteum Persisten,5000 ml dengan CAPRIGLADIN INJ; @10000 ml deng...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

In [ ]:
# df = pd.read_csv("Diagnosa.csv")

# # cek kolom
# print(df.columns)

AUGMENTASI DATA

In [ ]:
!wget https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.id.300.bin.gz
!gunzip cc.id.300.bin.gz

--2026-01-06 01:07:05--  https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.id.300.bin.gz
Resolving dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)... 3.163.189.51, 3.163.189.96, 3.163.189.14, ...
Connecting to dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)|3.163.189.51|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4507049071 (4.2G) [application/octet-stream]
Saving to: ‘cc.id.300.bin.gz’

cc.id.300.bin.gz    100%[===================>]   4.20G  90.4MB/s    in 40s

2026-01-06 01:07:45 (107 MB/s) - ‘cc.id.300.bin.gz’ saved [4507049071/4507049071]

In [ ]:
ft_model = fasttext.load_model("cc.id.300.bin")
def get_synonym_fasttext(word, model, topn=5):
    try:
        neighbors = model.get_nearest_neighbors(word, k=topn)
        return [w for _, w in neighbors]
    except:
        return []

In [ ]:
def synonym_replacement_ft(text, model):
    if not isinstance(text, str):
        return text

    words = text.lower().split()
    new_words = words.copy()

    for i, word in enumerate(words):
        synonyms = get_synonym_fasttext(word, model)
        if synonyms:
            new_words[i] = random.choice(synonyms)

    return " ".join(new_words)

In [ ]:
# Menukar posisi kata secara acak
def word_swap(text):
    words = text.split()
    if len(words) < 2:
        return text

    i, j = random.sample(range(len(words)), 2)
    words[i], words[j] = words[j], words[i]
    return " ".join(words)

In [ ]:
# Menghapus baris data yang kosong
df = df.dropna(subset=['Gejala', 'Diagnosa', 'Penanganan'])

In [ ]:
df['Gejala'] = df['Gejala'].astype(str)
df['Diagnosa'] = df['Diagnosa'].astype(str)
df['Penanganan'] = df['Penanganan'].astype(str)

In [ ]:
def augment_gejala(text):
    augmented = set()
    augmented.add(text.lower())
    augmented.add(text.replace(",", " "))
    augmented.add(" ".join(text.split()))
    return list(augmented)

In [ ]:
def augment_gejala(text):
    words = text.split()
    augmented = set()
    augmented.add(text)

    if len(words) > 3:
        idx = random.randint(0, len(words)-1)
        augmented.add(" ".join(words[:idx] + words[idx+1:]))

    return list(augmented)

In [ ]:
import random
df = df.dropna(subset=['Gejala'])

augmented_rows = []

for row in df.itertuples(index=False):
    for g in augment_gejala(row.Gejala):
        augmented_rows.append(
            {
                "Gejala": g,
                "Diagnosa": row.Diagnosa,
                "Penanganan": row.Penanganan,
            }
        )

df_aug = pd.DataFrame(augmented_rows)

In [ ]:
print("Jumlah data asli     :", len(df))
print("Jumlah data augmented:", len(df_aug))

df_aug.head()

Jumlah data asli     : 504
Jumlah data augmented: 744

,Gejala,Diagnosa,Penanganan
0,Abses,Abses,1.000 unit dengan GUSANEX dan 8.000 ml dengan ...
1,"Anemia, Anorexia, Bulu Kusam, Demam, Diare, Ga...",Avitaminosis,1.000 bolus dengan PYRONIL-2500 BOLUS dan 8.00...
2,"Anemia, Anorexia, Bulu Kusam, Demam, Diare, Ga...",Avitaminosis,1.000 bolus dengan PYRONIL-2500 BOLUS dan 8.00...
3,"Bulu kusam,Gatal,Kelainan kulit,Perkulitan",Babesiosis,8000 gram dengan TRYPONIL; @3000 ml dengan Int...
4,"Anorexia, Demam, Demam, Demam, Diare, Durasi g...",Bovine Ephemeral Fever,10.000 ml dengan B-SANPLEX dan 1.000 bolus den...

PRE PROCESSING DATA

In [ ]:
stemmer = StemmerFactory().create_stemmer()
stopword_factory = StopWordRemoverFactory()
stopwords = set(stopword_factory.get_stop_words())

In [ ]:
def preprocess_text(text):
    # 1. lowercase
    text = text.lower()

    # 2. hapus angka & simbol
    text = re.sub(r'[^a-z\s]', ' ', text)

    # 3. tokenisasi
    tokens = text.split()

    # 4. stopword removal
    tokens = [t for t in tokens if t not in stopwords]

    # 5. stemming
    tokens = [stemmer.stem(t) for t in tokens]

    return " ".join(tokens)

In [ ]:
df_aug['Gejala_Preprocessed'] = df_aug['Gejala'].apply(preprocess_text)

In [ ]:
df_aug[['Gejala', 'Gejala_Preprocessed']].head(10)

,Gejala,Gejala_Preprocessed
0,Abses,abses
1,"Anemia, Anorexia, Bulu Kusam, Demam, Diare, Ga...",anemia anorexia bulu kusam demam diare ganggu ...
2,"Anemia, Anorexia, Bulu Kusam, Demam, Diare, Ga...",anemia anorexia bulu kusam demam diare ganggu ...
3,"Bulu kusam,Gatal,Kelainan kulit,Perkulitan",bulu kusam gatal lain kulit kulit
4,"Anorexia, Demam, Demam, Demam, Diare, Durasi g...",anorexia demam demam demam diare durasi gejala...
5,"Anorexia, Demam, Demam, Demam, Diare, Durasi g...",anorexia demam demam demam diare durasi gejala...
6,Anestrus,anestrus
7,"gelisah, Janin yang terlilit tali pusar, Kelua...",gelisah janin lilit tali pusar keluar cair dar...
8,"gelisah, Janin yang terlilit tali pusar, Kelua...",gelisah janin lilit tali pusar keluar cair dar...
9,Rahim bernanah,rahim nanah

In [ ]:
df_aug.to_csv("dataset_preprocessed.csv", index=False)

TF IDF

In [ ]:
tfidf = TfidfVectorizer(
    max_df=0.95,
    min_df=2
)

tfidf_matrix = tfidf.fit_transform(df_aug['Gejala_Preprocessed'])

LSI

In [ ]:
n_components = 100
svd = TruncatedSVD(n_components=n_components, random_state=42)

lsi_matrix = svd.fit_transform(tfidf_matrix)

COSINE SIMILARITY

In [ ]:
def cari_diagnosa_interaktif(query, top_k=5):
    # Preprocessing query
    query_clean = preprocess_text(query)
    query_tfidf = tfidf.transform([query_clean])
    query_lsi = svd.transform(query_tfidf)

    # Cosine similarity
    similarity = cosine_similarity(query_lsi, lsi_matrix)[0]

    df_temp = df_aug.copy()
    df_temp['Similarity'] = similarity

    # Ambil gejala terbaik per diagnosa
    idx = df_temp.groupby('Diagnosa')['Similarity'].idxmax()
    ranking = df_temp.loc[idx][
        ['Diagnosa', 'Penanganan', 'Gejala', 'Similarity']
    ]

    # Threshold
    THRESHOLD = 0.25
    ranking = ranking[ranking['Similarity'] >= THRESHOLD]

    # Sorting & ranking
    ranking = ranking.sort_values(
        by='Similarity', ascending=False
    ).reset_index(drop=True)

    ranking['Rank'] = ranking.index + 1

    # Top-K
    ranking = ranking.head(top_k)

    return ranking[['Rank', 'Gejala', 'Diagnosa', 'Penanganan', 'Similarity']]

In [ ]:
query = input("Masukkan gejala sapi: ")
hasil = cari_diagnosa_interaktif(query)
hasil

Masukkan gejala sapi: liur berlebihan, borok pada kulit, bulu rontok, demam

,Rank,Gejala,Diagnosa,Penanganan,Similarity
0,1,"Anorexia, Borok Perkulitan, Bulu Rontok, Perku...",Scabies,"0.0500 dengan ivomec super, 3.000 ml dengan in...",0.719761
1,2,"Anorexia,Demam,Liur berlebihan",Feline Viral Rhinotracheitis,0.500 ml dengan PENSTREP-400; @ 0.500 ml deng...,0.535370
2,3,"Anorexia,Demam,Liur berlebihan,Sempoyongan",Feline Calicivirus,0.300 ml dengan MEDOXY-L; @1000 ml dengan INJE...,0.435735
3,4,"Demam, Liur berdarah",Stomatitis,10000 ml dengan SULPIDON INJEKSI; @8000 ml den...,0.420966
4,5,"Anorexia, Lemah, Liur berlebihan,",Keracunan,2000 ml dengan COLIBACT INJEKSI; @1000 ml deng...,0.369236

In [ ]:
if hasil.empty:
    print("Tidak ditemukan diagnosa yang relevan.")
else:
    hasil